### ISSUE TITLE
Failure to install module using Foundry VTT's Install Module

### ISSUE THREAD

**Issue by KennethEMarks** [Parasrah/ddb-importer#1]
When importing this module using Foundry VTT's Install Module feature, failure to provide a valid manifest file is returned as an error. I suspect the manifest URL is pointing to an invalid URL (i.e.  https://github.com/parasrah/ddb-importer/releases/download/latest/module.json gives a 404 error).

**Comment by Parasrah** [comment]
Hey @KennethEMarks yeah I think this is a bug, I mostly just tweaked what existed already from the source repo, but I haven't enabled the build pipeline so the way the releases are structured might be different.

I managed to successfully install the module using the raw link `https://raw.githubusercontent.com/Parasrah/ddb-importer/master/module.json`, although you likely won't be able to use the "update" feature of FoundryVTT to update this module until this is resolved.

I will try to get this taken care of, thanks for reporting!

**Comment by KennethEMarks** [comment]
Awesome! Sounds great!

I was digging into your elixir code for the proxy for grins and giggles last night and I managed to trace through some of the calls to the DnD Beyond endpoints and verified them through Postman. You’re right, elixir is an incredibly clean language. I can see why you like to use it.

I’ll try and see if I can get the proxy running tonight or tomorrow.

Best regards,

- Ken

**Comment by Parasrah** [comment]
Hey @KennethEMarks, there will be a new release of the proxy releasing within the next couple minutes that should fix feats, races and a minor issue I identified with the image proxy, in case you're in the middle of testing it out right now

Yeah I really enjoy Elixir, it's a very well designed language

**Comment by KennethEMarks** [comment]
Hi Brad,

I waited until this afternoon to start in with some testing. I just downloaded release v0.4.0 and attempted to run it on the command line, in the folder I unzipped it into with the following command:

bin/ddb_proxy start

and I received the following error:

Kenneths-MacBook-Pro:ddb-proxy kemarks$ bin/ddb_proxy start
bin/ddb_proxy: /Users/kemarks/Documents/Development/Gaming/DnD/FoundryVTT/Modules/ddb-proxy/releases/0.3.0/elixir: /nix/store/9ywr69qi622lrmx5nn88gk8jpmihy0dz-bash-4.4-p23/bin/sh: bad interpreter: No such file or directory
bin/ddb_proxy: line 57: /Users/kemarks/Documents/Development/Gaming/DnD/FoundryVTT/Modules/ddb-proxy/releases/0.3.0/elixir: Undefined error: 0

Do I need to install something?

I am running on a MacBook Pro under Mojave 10.14.6 and I did set all the environment variables in my .bash_profile.

Thanks again for your work on the development of this and for letting me do some testing on it.

- Ken

**Comment by Parasrah** [comment]
Hey @KennethEMarks, I've moved the issue over to the `ddb-proxy` repo [here](https://github.com/Parasrah/ddb-proxy/issues/14) just so I can better track this

**Comment by Parasrah** [comment]
Hey @KennethEMarks the issue with the `module.json` to install from the `Manifest URL` should be addressed with the most recent release. Added notes to the README how to install per your suggestion as well

**Comment by KennethEMarks** [comment]
Hi Brad,

Sorry I didn’t get back to you sooner. I was at an all day event today. Also, I’m very happy to keep testing as well. I’ll take a look at your latest instructions and give it another go shortly. 

- Ken

**Comment by KennethEMarks** [comment]
Hi Brad,

I just did some testing with the v7.0.0 release. Here are the steps I followed:

Cloned https://github.com/Parasrah/ddb-proxy.git <https://github.com/Parasrah/ddb-proxy.git> repository.
Cd’d into ddb-proxy folder and ran a git checkout on the v7.0.0 release.
Installed nix using curl: curl -L https://nixos.org/nix/install | sh
Ran nix-build and got the following error:
Kenneths-MacBook-Pro:ddb-proxy kemarks$ ls
README.md	config		flake.nix	mix.lock	test
Taskfile.yml	default.nix	lib		nix
VERSION		flake.lock	mix.exs		scripts
Kenneths-MacBook-Pro:ddb-proxy kemarks$ pwd
/Users/kemarks/Documents/Development/Gaming/DnD/FoundryVTT/proxy/ddb-proxy
Kenneths-MacBook-Pro:ddb-proxy kemarks$ nix-build 
unpacking 'https://github.com/NixOS/nixpkgs/archive/5438e11ea34adf2b8111d80e360442077476ff53.tar.gz'...
error: cannot coerce null to a string, at /Users/kemarks/Documents/Development/Gaming/DnD/FoundryVTT/proxy/ddb-proxy/nix/build-mix.nix:35:28
(use '--show-trace' to show detailed location information)

Re-ran with —show-trace and got this:
Kenneths-MacBook-Pro:ddb-proxy kemarks$ nix-build --show-trace
error: while evaluating the attribute 'LOCALE_ARCHIVE_2_11' of the derivation 'ddb-proxy-0.7.0' at /nix/store/d6jjcjh47npcp4jg6cn1c0cxcgr0fxif-source/pkgs/stdenv/generic/make-derivation.nix:192:11:
cannot coerce null to a string, at /Users/kemarks/Documents/Development/Gaming/DnD/FoundryVTT/proxy/ddb-proxy/nix/build-mix.nix:35:28

Let me know if I should use a previous version, or if there is anything else you’d like me to try.

Best regards,

- Ken

**Comment by Parasrah** [comment]
Hey @KennethEMarks no worries! There isn't any rush at all for you to test this stuff, no need to feel obligated in any way to respond quickly or anything. It's no pressure for me, I just want to get it working for you haha

I've opened up [ddb-proxy#20](https://github.com/Parasrah/ddb-proxy/issues/20) to address this, will try to get you unblocked! It didn't occur to me it would build differently on MacOS haha

**Comment by KennethEMarks** [comment]
Hi Brad,

I successfully built release v0.7.8. Best I can tell, I was able to import everything but the items.

- Ken

**Comment by KennethEMarks** [comment]
Hi Brad,

I got items to import as well. I had the endpoint misconfigured.

- Ken

**Comment by Parasrah** [comment]
@KennethEMarks awesome news! Glad it worked for you!
